### ISSUE TITLE
Testing 6-to-3 balancers fails

### ISSUE THREAD

**Issue by seyfahni** [tzwaan/factorio_balancers#4]
Testing my strange (and very first truly self-made) `6-to-3` balancer results in some strange error about an illegal configuration. The `6-to-3` balancer from the [balancer blueprint book](https://pastebin.com/igs2CvVd) produces a similar error. Simple `4-to-4` balancer do work properly.

I suppose this program currently only analyzes `n-to-m` balancers where `n < m`?

### My balancer
```
balancer_test --string '0eNqtXO1uIkkMfJf5TVbt/m5e5bRaJbskOxILCCZ3F0W8+wFJdASmGHdXfkUJpOyudttu2zOv3cPyebHZ9quhm792/c/1atfN/3rtdv3T6n55/Nvwsll0864fFn+6Wbe6/3P87fF+N9wN2/vVbrPeDncPi+XQ7Wddv/q1+Leby/77rFushn7oF29wp19efqye/zwstocv3ASadZv17vC/69VR/hHPhG9h1r108zux6VvY72dXkJaAjOOQrhYyTmrpayHTJGQgtAQLj58hnw+7un3arg8/NXoeQWcfZrN+HjbPR9u4EpKIDQvjemcC0o9DFoJdoKUYwgjCidxf/Xbx8+0rcUyCUBvozzewX4H9k+oTl2uXUX0AS60ET0gAFiMXB3K3WfbDcPhkzFg+sNxJ28d+efzivNve/3P32O9+H/7n7QD9OLjo9fYg5vhh//R7fEcazu3ZCbCXjHmFEST9YvPXLjYTJ9OCrSvEyQSY1qgZOjqGL2TINniBfGkOk27cWuIIIc5cteZi6jX3hAUJ0DwQFoQwI6GnAZiJ0BNhZsIS0NoLEWSMJgQ4Q2itk1Cb7Z7bsqgk1J5BkVoJjliDjiVPrEEnofZsiq1lqT4An8swOr/lUn2CIbkioiwXj+OCiZArBdyxSn0C8SWL8YaJjqflTKdHXuqD/9eszjIRVLs6135kkT14wg2cmBvDrA7K/n/MdHnw7ZiE2H7zFFQqSITW4GLvM3NDkIhvCNhdeeIKjbgJhrngvu/ppOZBCM3BDgTbnnhd8z8WhIKjHJuWG+LmDHc1EJiI70g5Qi0bqV6K1EvJ7UmY0nYK4X1VEqIhvBooqEWinAwxLaEnqAxFR+jpVez6+rMfP3PxWYbCKiNx5YXsE1fea6bGInYkLsBwfzPleW+wD1OwWAiXqSqRpoZQWy43Y7oZIJSbDqp8NRHXZGSpiSpVqelhsmJgrYm4Duu8Uao9xeJqJRBNpKOwUV6ILpKAgmZicmCgZ+ZyYNfi6zOTEVuNX86WWtW1jGm3kLmE2al8T/aUG3UNsSEHal3KKnqORFLqNIc8J0ICOJA5Uwn7DTO7wVRhqoNKOyuG8LnA0xQhIgXYgGIJPREmk1+DBkTxDcVW0CApxKgG1I+a1RDRGVVDlxeSkNs7OiKaEFKYnPhKgh+d4CCaRmI0ixBDdI2QsYhhMmBVC0QM0Sm6pmacfU85b6MbbzFMfqzkikmQ4R4nQm+DQDOhKQQt7f7agP6B1E9XnYFmBErkvVhTKtU1RZefiRBjjJgQYpDRZN0MW2gPFJjzSIAq9a4IluVMYw00UQB+t5dJEUQFGLJuDVMkeed9eh5RmLDwWcqN81Q98HTmXzFDrt2/YlDPXDj0hARCd+RgLNFRNQmBJsIVJtX5sZly6klp6hVTE+kDG3TIxFGTEFqVnTAFELUUW+F8J4khUllog8yck1ENI4jTTyAfE5sJEiLh7pIqn3eJcCCQ50zoHXU8F0LvqKLGV5dzfK3H8kKIQFbjicdxTFCx74lqj0Gz+56YCTboeQ9PdEgxKNEiNV7HMNEjxQwT9R9MBlHygaDBEJrCh0OE0BSCUtN+JigTvUDM+2GWPRFkVU1CqZ4rOtdbKYKo5Bjdo0pBf688D2UqaKK6o/Ql9ZNFftp2IhMd0WFipomMQ6BMPERPK0WmsgM1ZSIg1JSp5UBNI+FKVZ1Hial+fhuTkCkvrev/SSxUFUQpJVU81WaniGkZ/rH1KhMdR2iDl+M/t3jwkzx4wp05lRuuH/oJN0SMXlnqp34uXJ1iFdUXxnhDxPgqiCkgg1oziWl4oC5KNoTDRprWD/qkz6DTm5gtoTckwxF6Q1BPRC8lGcToO95Eptmh61JXz+ac660UwTQ9IDVMmwOB1s/emGnjqx++EQUo08OAy28YhXWXB2X6Flo8oTskhOlhqJ4+lRKJ6A45TwSoUu+sT3HOY6AGuhBxXDViYU37OEAp6I0O7TfEkhFmezTEerYHQ4zZfj3Ea2+vj2LM9tiH157aMaGeudm9Yz1Ls4csqikBK4Zw9UX3dLGVioen3QTN0l5/KeiFY9LegCgRYRLHC+pJHC+I2d59wGtvbzdgzPZuA157e7OhqBq41rZ3HiATtr3xgDFtc8KrZaK95aCV0N5/KFEnob39oJXQ3qOHVm7bm/IYs70nr2WivSUPrdwRKWRAmO0DpRiz/dUCGNO1eyKI2f7qAIwZ2k/xCfP77O0Np/OzF6LOur8X292bsWXxyZcU02EnQtzv/wP9qX+O'
```
```
                  
      ^^^         
      ^^▓         
      ^^<<<       
      ^ ▓ ^       
      ╒╕╒╕╒╕      
      ▓^^▓^▓      
       ^^ ^<<<    
       ^^<<<<▓    
       ^ ▓ ▓^     
      ╒╕╒╕╒╕^     
     >^^▓▓^▓▓     
     ^▓^< ^<<     
     ^^▓^▓<▓^     
     ^<>^ ▓▓^<<   
      ^^▓▓▓< ▓^   
      ^>▓▓ ^▓^^   
      ^^▓>V^<<^   
      ╒╕╒╕>V▓^^   
      ^^▓^╓<^^^   
      ^^<<╙▓▓▓^   
      ^<▓▓▓^>V^<  
       ╒╕╒╕╒╕>V^  
      >^^^^▓^╓<^  
      ^>^^^<<╙>^  
      ^^ ^<▓▓▓^>V 
      ^^  ╒╕╒╕╒╕>V
      ^^>>^^^^▓^╓<
      ^^^>>^^^<<╙ 
      ^^^^  ^<▓   
      ^^^^   ╒╕   
      ^^^^>>>^^   
      ^^^^^>>>^   
      ^^^^^^      
Traceback (most recent call last):
  File "/home/niklas/.local/bin/balancer_test", line 75, in <module>
    balancer = Balancer(string=string, verbose=args.verbose)
  File "/home/niklas/.local/lib/python3.8/site-packages/factorio_balancers/balancer.py", line 60, in __init__
    self.recompile_entities()
  File "/home/niklas/.local/lib/python3.8/site-packages/factorio_balancers/balancer.py", line 170, in recompile_entities
    raise IllegalConfigurations(*exceptions)
factorio_balancers.exceptions.IllegalConfigurations: <exception str() failed>
```

### Blueprint book balancer
```
balancer_test --string '0eNqlVtuugyAQ/BeetRFUvPzKyYnRlvaQWDSITZvGfz+rppdUqIU+1SI7szvuDlxRVfeslVwolF8R3zaiQ/nPFXX8IMp6XFOXlqEcnbhUPax4SJTHcWHe4VM0eIiLHTujHA+eRWT4FEmGXw8xobjibE5g+nMpRH+smAToezQ7t5J1na9kKbq2kcqvWK0AvW06CG/ESA2QPt7EHrrAA9nEwLTjkm3n99GY5wsBsScgNwL8CUH4RQULAqohiKwJgmeFNIixfcqBUXRdynRB0LU1VwreLZN9SKFBSqxTxSvFp9aIZAUxs6iWvK0WB190a/D6ZYiOAVske2/U4APgLwbts8zDL7o2MOgdWaiB30Mth6oHD5QH2cDvWoJLBbybzXLR9grpGKmzMZhqSNxnwwSZOg+wCTFzEJqs69z0yiA0sZ/K0DiUOrsk2JnAIBIhNmM+m5LBk0joPtgGwySR+5lpgoytj5z58N3zetyTox0bL0lK9tOH8tu6FGIKnhujgMtUI4ESttZsr28U6m5RproS5yE3IabWx5W7UpIf/vRSZc6+YKgrDJzNa0KEiypX7Ajhj6uzh+oSQmGNFmFRlVDpdqr0xGQ3+0eKoyTKEprggMZ0GP4BgDPVfw=='
```
```
            
      V<^^^ 
     V<╒╕╒╕ 
     >╖^╒╕^<
     >╜▓^^▓^
     ╒╕╒╕╒╕ 
     ^^^^^^ 
Traceback (most recent call last):
  File "/home/niklas/.local/bin/balancer_test", line 75, in <module>
    balancer = Balancer(string=string, verbose=args.verbose)
  File "/home/niklas/.local/lib/python3.8/site-packages/factorio_balancers/balancer.py", line 60, in __init__
    self.recompile_entities()
  File "/home/niklas/.local/lib/python3.8/site-packages/factorio_balancers/balancer.py", line 170, in recompile_entities
    raise IllegalConfigurations(*exceptions)
factorio_balancers.exceptions.IllegalConfigurations: <exception str() failed>
```

## System
Python 3.8.6
on
Arch Linux

**Comment by tzwaan** [comment]
The tool should be able to analyze any N to M balancer or lane balancer. This looks like a bug.

IllegalConfiguration is raised when 2 belts are facing eachother, for example, or when you're sideloading onto a splitter, but in this case it seems like something is going wrong in the checker, since normally the exception should show actual information about where the error is, but I don't think there should be any errors.

I don't know when I'll be able to take a look at this, since I'm quite busy, but I'll add it to the to-do list.

**Comment by seyfahni** [comment]
I guess I now know the source of that error: Some splitters have a filter set (either to fish with mine or to deconstruction planner with the blueprint books one).

**Comment by tzwaan** [comment]
Ah, yes, I haven't actually implemented filters yet (as far as I remember). Though I don't think it should be crashing because of it (but clearly it does).
