### ISSUE TITLE
Crashes unless silent

### ISSUE THREAD

**Issue by ScarabWasTaken** [tzwaan/factorio_balancers#7]
Unless I add --silent the balancer_test script always crashes at the end.

`>python balancer_test -nb -es --string 0eNqlWFtugzAQvIu/aeUnr6tUVZW0bmqJADKmahRx95oEqWnDUtv7FRHBzOCd8S4+k30z6t6a1pH6TMxr1w6kfjqTwRzaXTP/5069JjUxTh9JRtrdcb7SX73Vw/Dg7K4d+s66h71uHJkyYto3/UVqNmXBIEPfGOe0vXmcT88Z0a0zzuiroMvF6aUdj3t/Z83+k5KRvhv8410783tIwatHlZETqf3vNMv7A8lhYfdggl6gSg81i+5H9+JXsbMe0AM0+n1ejDsKEa9a0G3VMgGSLZDlOqRCQAIq8wRIvq2yuIMcvXfswXb+91/Q6lK4xZbd6HwB1wpWJpGIOJIqynhyy3jWHD5WORhNqIDcLirDhJAxAJRjQCkAigkeqFRG1Y3/gGWLGe4rF1VSFcXPflYoih/ayxgm04uMN2P16/UGvkZRJFCIOIoSkQvQbhXGwwJoTxQDygFQlrTB0VutATsc50k0LJZGpCSCA4mAjM8lqvP8fplL3FZZFKr1hLKgQgyZChVb/je2+RoFKrZQwioMaJBugQqxXNctWEojUlu2j5lpOaa3yqBVE4iJNJBCYjyrgMLEdWhxqze8MOCAIHKMn6F3KjCgkINLTCwKABTVhfOQ6UFSXF8rgjZpiWzSgSyoHIctFyrHOfABjEou4B2pMH0RAs1TtoN8c2Bfo0ElFNKOarhQ6aqEIxdWRs5riqa0R+hshCV8rIOSlxo+Z9eTsfrmNC4jn9oO1yiVTBYVLxRTTOR0mr4BhMSSHg==

Testing a 6 - 6 balancer.
  Extensive throughput sweep
   -- Progress |############################### | 99% - 0:00:01Traceback (most recent call last):
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\balancer_test", line 94, in <module>
    results = balancer.test(
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\factorio_balancers\balancer.py", line 615, in test
    unlimited, worst = self.test_throughput_unlimited(
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\factorio_balancers\balancer.py", line 529, in test_throughput_unlimited
    results = self.throughput_sweep(**kwargs)
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\factorio_balancers\balancer.py", line 525, in throughput_sweep
    bar.finish()
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\factorio_balancers\balancer.py", line 42, in finish
    self.bar.finish(*args, **kwargs)
  File "C:\Users\Scarab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\factorio_balancers\balancer.py", line 22, in finish
    self.clearln()
AttributeError: 'MyBar' object has no attribute 'clearln'
←[?25h`

**Comment by tzwaan** [comment]
Looks like some of the api in the progress package changed. Try downgrading that package to a previous version.

**Comment by ScarabWasTaken** [comment]
Fixed thanks, downgraded to Progress 1.5
